name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t lorenzocampanella/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true lorenzocampanella/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-459301

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-k8s
          location: us-east1-b

      - name: Build
        run: |-
          docker build -t lorenzocampanella/multi-client:latest -t lorenzocampanella/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t lorenzocampanella/multi-server:latest -t lorenzocampanella/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t lorenzocampanella/multi-worker:latest -t lorenzocampanella/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push lorenzocampanella/multi-client:latest
          docker push lorenzocampanella/multi-server:latest
          docker push lorenzocampanella/multi-worker:latest

          docker push lorenzocampanella/multi-client:${{ env.SHA }}
          docker push lorenzocampanella/multi-server:${{ env.SHA }}
          docker push lorenzocampanella/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=lorenzocampanella/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=lorenzocampanella/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=lorenzocampanella/multi-worker:${{ env.SHA }}
